name: Share data between jobs

on: [push]

jobs:
  compute:
    name: Compute
    runs-on: ubuntu-latest
    steps:
      - name: Compute
        run: |
          echo "Hello artifacts" > hello.txt
          echo "Moar! artifacts" > moar.txt
          echo "Lotta artifacts" > lotta.txt
          mkdir my-data
          mkdir my-data/nested/
          mv *.txt my-data/nested/
          touch my-data/nested/foo
          tar vzcf my-data.tgz my-data
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-data-artifact
          path: my-data.tgz
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: my-data/
          key: my-data

  display:
    name: Display
    needs: compute
    runs-on: ubuntu-latest
    steps:
      - name: Download my data
        uses: actions/download-artifact@v3
        with:
          name: my-data-artifact
      - name: Display the results
        run: |
          ls *
          tar vzxf my-data.tgz
          cat my-data/nested/*.txt

  display-2:
    name: Display but using cache
    needs: compute
    runs-on: ubuntu-latest
    steps:
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: my-data/
          key: my-data
      - name: Display the results
        run: |
          pwd
          ls -la
          cat my-data/nested/*.txt

  conditions-test:
    name: Tests conditions on matrices
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Run this always
        run: echo "This is always run"
      - name: Run this only on pushes to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && ${{ matrix.os=='ubuntu-latest' }}
        run: echo "This runs only on pushes to main"
